version: '3.8'

services:
  nodejs-server:
    container_name: backend-app
    build:
      context: ../
      dockerfile: docker/Dockerfile
      pull: true
    pull_policy: never
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - .env
    command: >
      bash -c "npm i && npm start"
