version: '3.8'

services:
  nodejs-server:
    container_name: backend-app
    build:
      context: ../
      dockerfile: docker/Dockerfile
      pull: true
    pull_policy: never
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - PORT=5000
      - DB_URL=${DB_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - API_URL=${API_URL}
      - CLIENT_URL=${CLIENT_URL}
      - CODE_PART_1_AES_KEY=${CODE_PART_1_AES_KEY}
      - CODE_PART_2_AES_KEY=${CODE_PART_2_AES_KEY}
      - FILES_AES_KEY=${FILES_AES_KEY}
    command: >
      bash -c "npm i && npm start"
