name: Simple auth app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image and start Docker Compose
        run: |
          sudo cp /etc/.env ${PWD}/docker
          cd docker && docker compose build
          docker compose up -d

      - name: Clear dangling images
        run: sudo docker rmi $(sudo docker images -f "dangling=true" -q)
