name: Simple auth app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: cd docker && docker compose build

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Clear dangling images
        run: sudo docker rmi $(sudo docker images -f "dangling=true" -q)
